name: eimunisasi
description: Aplikasi untuk imunisasi anak.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.1.1+10

environment:
  sdk: ">=3.2.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # SUPABASE
  supabase_flutter: ^2.6.0

  shared_preferences: ^2.3.2
  after_layout: ^1.0.7+2
  provider: ^6.1.2
  snack: ^2.0.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  image_picker: ^1.1.2
  country_code_picker: ^3.0.0
  fl_chart: ^0.68.0
  math_expressions: ^2.6.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  qr_flutter: ^4.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  formz: ^0.7.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  keyboard_dismisser: ^3.0.0
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1
  go_router: ^14.2.7

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  firebase_core_platform_interface: ^5.2.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  firebase_storage_mocks: ^0.7.0
  firebase_auth_mocks: ^0.14.0
  mock_exceptions: ^0.8.2
  fake_cloud_firestore: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
